version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - pip install pytest pytest-cov
  build:
    commands:
      - echo "Running tests..."
      - pytest tests/ --cov=src/
      - echo "Building deployment package..."
      - cd src/
      - zip -r ../function.zip .
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - function.zip
    - appspec.yml
  discard-paths: yes